[project]
name = "sanctions-checker"
version = "0.1.0"
description = "Checking for Sanctions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "db-dtypes>=1.4.4",
    "google-cloud-bigquery>=3.38.0",
]
